### ISSUE TITLE
Investigate Windows build from source

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/yasm-feedstock#2]
YASM appears to provide a [CMakelists](https://github.com/yasm/yasm/blob/master/CMakeLists.txt) as well as a [vc9](https://github.com/yasm/yasm/tree/master/Mkfiles/vc9) solution. It might not be too hard to get it building from source rather than just downloading the pre-built release.

**Comment by jakirkham** [comment]
Proposal in PR ( https://github.com/conda-forge/yasm-feedstock/pull/9 ).
